name: release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: build
    runs-on: [ubuntu-latest]
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v1
      
      - name: Setup docker buildx
        uses: crazy-max/ghaction-docker-buildx@v0.1.0
      
      - name: Run docker login
        run: echo "${{ secrets.DOCKER_REPOSITORY_TOKEN }}" | docker login --username "${{ secrets.DOCKER_REPOSITORY_USERNAME }}" --password-stdin
      
      - name: Generate tag name
        id: tag
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const tag = context.payload.ref.replace(/^refs\/[a-zA-Z]+\/v/, '');
            return `${tag}`;

      - name: Run docker buildx (Standalone)
        run: |-
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/s390x \
            --output "type=image,push=true" \
            --tag "jakehilluk/unifi:v${{ steps.tag.outputs.result }}" \
            --build-arg unifi_version="${{ steps.tag.outputs.result }}" \
            --build-arg self_contained="False" \
            --file Dockerfile.buildx \
            .
      - name: Run docker buildx (All in one)
        run: |-
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/s390x \
            --output "type=image,push=true" \
            --tag "jakehilluk/unifi:v${{ steps.tag.outputs.result }}-all-in-one" \
            --build-arg unifi_version="${{ steps.tag.outputs.result }}" \
            --build-arg self_contained="True" \
            --file Dockerfile.buildx \
            .
  
  release:
    needs: [build]
    runs-on: [ubuntu-latest]
    steps:
      
      - name: Automatic Releases
        uses: marvinpinto/action-automatic-releases@v0.2.2
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          title: "UniFi v${{ steps.tag.outputs.result }}"
          automatic_release_tag: false
          draft: false
          prerelease: false
    
